---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8040"
spec:
  type: ClusterIP
  ports:
  - port: 8040
    targetPort: 8040
  selector:
    app: notification-deployment