apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: default
spec:
  serviceName: kafka-service
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:7.5.0
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 9092 
        env:
          - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
            value: "true"
          - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
            value: "1"
          - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
            value: "1"
          - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
            value: "1"
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: "zookeeper-service:2181"
          - name: KAFKA_ADVERTISED_LISTENERS
            value: "PLAINTEXT://kafka-service:9092"
          - name: KAFKA_LISTENERS
            value: "PLAINTEXT://0.0.0.0:9092"
          - name: KAFKA_BROKER_ID
            value: "1"
        resources:
          limits:
            memory: "400Mi"
        volumeMounts:
          - mountPath: /var/lib/kafka/
            name: kafka-storage-pvc
    
      restartPolicy: Always
      volumes:
        - name: kafka-storage-pvc
          persistentVolumeClaim:
            claimName: kafka-storage-pvc 