apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-deployment
  template:
    metadata:
      labels:
        app: product-deployment
    spec:
      containers:
        - name: product
          imagePullPolicy: Always
          image: shogun101/ecommerce-product-service:latest
          ports:
            - containerPort: 8050
          env:  
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://config-service:8888" 
          command: ["/bin/sh", "-c"]
          args:
            - |
              while ! curl -s http://discovery-service:8761/actuator/health | grep '"status":"UP"'; do
                echo "Waiting for config-service to be ready..."
                sleep 5
              done
              echo "product-service is ready. Starting product service."
              java -jar /app/app.jar 
          resources:
            limits:
              memory: "400Mi"