apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-payment-pv 
spec:
  capacity:
    storage: "100Mi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/storage/postegres"
  claimRef:
    name: postgres-payment-pvc
    namespace: default
