apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-payment-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "100Mi"
  volumeName: postgres-payment-pv
