apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres-payment
  name: postgres-payment-service
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres-payment
