apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-customer-pv
spec:
  capacity:
    storage: "100Mi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/storage/mongodb"
  claimRef:
    name: mongo-customer-pvc
    namespace: default