apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-notification-pv
spec:
  capacity:
    storage: "100Mi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/storage/mongodb"
  claimRef:
    name: mongo-notification-pvc
    namespace: default