apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-notification-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "100Mi"
  volumeName: mongo-notification-pv