apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-product-pv
  labels:
    app: postgres-product
spec:
  capacity:
    storage: "100Mi"
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/data/storage/postegres"
  claimRef:
    name: postgres-product-pvc
    namespace: default