apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-product-pvc
  labels:
    app: postgres-product
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "100Mi"
  volumeName: postgres-product-pv


