apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres-product
  name: postgres-product-service
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None
  selector:
    app: postgres-product
