apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-order-pv
spec:
  capacity:
    storage: "100Mi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/storage/postegres"

  claimRef:
    name: postgres-order-pvc
    namespace: default
