apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-order-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "100Mi"
  volumeName: postgres-order-pv
