apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-storage-pv
spec:
  capacity:
    storage: "100Mi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/storage/messageBroker"
  claimRef:
    name: zookeeper-storage-pvc
    namespace: default
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-storage-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "100Mi"
  volumeName: zookeeper-storage-pv
