apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-deployment
  template:
    metadata:
      labels:
        app: customer-deployment
    spec:
      containers:
      - name: customer
        imagePullPolicy: Always
        image: shogun101/ecommerce-customer-service:latest
        ports:
        - containerPort: 8090
        env:
          - name: SPRING_CONFIG_IMPORT
            value: "optional:configserver:http://config-service:8888"
        command: ["/bin/sh", "-c"]
        args:
          - |
            while ! curl -s http://config-service:8888/actuator/health | grep '"status":"UP"'; do
              echo "Waiting for config-service to be ready..."
              sleep 5
            done
            echo "customer-service is ready. Starting customer service."
            java -jar /app/app.jar 
        resources:
          limits:
            memory: "400Mi"