apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres-order
  name: postgres-order-service
spec:
  clusterIP: None
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres-order
