# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: ingress-domain
#   annotations:
#     kubernetes.io/ingress.class: "nginx"  
# spec:
#   ingressClassName: nginx
#   rules:
#   - host: ecommerce-api.com
#     http:
#       paths:
#       - path: /api
#         pathType: Prefix
#         backend:
#           service:
#             name: api-gateway-service
#             port:
#               number: 8222
 