apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/walidhabbach/Ecommerce-Microservice.git
    targetRevision: main
    path: kubernetes/infrastructure
    directory:
      recurse: true  
      exclude: '{argocd/*,keycloak/*,alert-manager/*}'
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
  